#!/usr/bin/env bash

REALNAME="Antsy Alien Attack Pico"
LOWERNAME="${REALNAME,,}"
FILENAME="${LOWERNAME// /-}"
ITCH_USER="wimpress"
ITCH_GAME="${FILENAME}"

if ! which butler ; then
  echo "ERROR! butler not found. Please install butler."
  exit 1
fi

if [ -e "${HOME}"/.config/itch/butler_creds ]; then
  VER=$(head -n1 exports/version.txt)
  for PLATFORM in cart deb dmg linux raspi wasm_crt windows snap; do
    case "${PLATFORM}" in
     cart)
       PLATFORM="p8"
       CHANNEL="pico-8"
       EXT="png"
       butler push "exports/${FILENAME}.${PLATFORM}.${EXT}" "${ITCH_USER}/${ITCH_GAME}:${CHANNEL}" --userversion "${VER}"
       ;;
     deb)
       PLATFORM="amd64"
       CHANNEL="linux_debian"
       EXT="deb"
       butler push "exports/${FILENAME}_${VER}_${PLATFORM}.${EXT}" "${ITCH_USER}/${ITCH_GAME}:${CHANNEL}" --userversion "${VER}"
       ;;
     dmg)
       PLATFORM=""
       CHANNEL="osx"
       EXT="dmg"
       butler push "exports/${FILENAME}.${EXT}" "${ITCH_USER}/${ITCH_GAME}:${CHANNEL}" --userversion "${VER}"
       ;;
     html*|wasm*)
       CHANNEL="html"
       EXT="zip"
       butler push "exports/${FILENAME}_${PLATFORM}.${EXT}" "${ITCH_USER}/${ITCH_GAME}:${CHANNEL}" --userversion "${VER}"
       ;;
     raspi)
       CHANNEL="linux_raspi"
       EXT="zip"
       butler push "exports/${FILENAME}_${PLATFORM}.${EXT}" "${ITCH_USER}/${ITCH_GAME}:${CHANNEL}" --userversion "${VER}"
       ;;
     snap)
       PLATFORM="amd64"
       EXT="snap"
       snapcraft upload "exports/${FILENAME}_${VER}_${PLATFORM}.${EXT}" --release stable
       ;;
     *)
       CHANNEL="${PLATFORM}"
       EXT="zip"
       butler push "exports/${FILENAME}_${PLATFORM}.${EXT}" "${ITCH_USER}/${ITCH_GAME}:${CHANNEL}" --userversion "${VER}"
       ;;
    esac
  done
else
  echo "WARNING! Not crednetial for Butler found. Skipping Itch publishing."
fi
